### ISSUE TITLE
Word of warning

### ISSUE THREAD

**Issue by ColinWaddell** [bazwilliams/python-taps-aff#1]
Just a quick warning. I'm currently re-writing taps-aff so your API will eventually break. Would you like me to ping you a message when I make the move?

The rewrite is here: https://github.com/ColinWaddell/tapsaff-django

There's a bunch of stuff I was planning doing for Alexa but decided the server-side was too far gone to keep appending to and a rewrite was the best way forward.

**Comment by bazwilliams** [comment]
No problem, ping me a message and I'll release an update. Thanks for the heads up!

**Comment by ColinWaddell** [comment]
So here's an example being served up by my dev setup: http://django.taps-aff.co.uk/api/Glasgow/

The final URL will be http://www.taps-aff.co.uk/api/Glasgow/

With any place name you're looking up after the ```/api/```

It'll probably be swapped over to the new implementation in the next couple if days. I'll keep you in the loop!

**Comment by ColinWaddell** [comment]
Got carried away. Finished the port tonight. 

Here's a pull request for an update to your request code: https://github.com/bazwilliams/python-taps-aff/pull/2
